### ISSUE TITLE
img lazy load error

### ISSUE THREAD

**Issue by jackPanyj** [toapi/toapi-pic#1]
when i test the demo, i find that the websit `https://pixabay.com`  used `lazy load tech` to show the hidden img, so i got this:
![image](https://user-images.githubusercontent.com/12585605/34511286-56a1ac0a-f095-11e7-9bde-b66234e3e525.png)
when the img not in the viewpoint , it set default img src of '/static/img/blank.gif', when scroll into view, it will replace it with the real img url.

**Comment by elliotgao2** [comment]
@jackPanyj Not an error.The result is needed to be cleaned by the clean method. Toapi can't be able to send an event to the PhantomJS at present, so we could only get the HTML without an event happening.

**Comment by jackPanyj** [comment]
@gaojiuli thanks for replay.
